[package]
name = "quantum-shield"
version = "0.1.0"
edition = "2021"
authors = ["valh4x"]
description = "Hybrid quantum-resistant cryptography using NIST-standardized post-quantum algorithms (Kyber, Dilithium)"
license = "MIT"
repository = "https://github.com/redasgard/quantum-shield"
keywords = ["cryptography", "post-quantum", "quantum-resistant", "kyber", "dilithium"]
categories = ["cryptography", "no-std"]
readme = "README.md"

[dependencies]
# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"

# Classical cryptography
rsa = "0.9"
sha2 = "0.10"
sha3 = "0.10"
aes-gcm = "0.10"

# Post-Quantum Cryptography (NIST-standardized)
pqcrypto-kyber = "0.5"
pqcrypto-dilithium = "0.5"
pqcrypto-traits = "0.3"

# Randomness
rand = "0.8"

# Optional async support
tokio = { version = "1.0", features = ["sync"], optional = true }

# Zeroization for secure memory handling
zeroize = { version = "1.7", features = ["derive"] }

# Security enhancements
subtle = "2.5"
rand_core = "0.6"

[dev-dependencies]
tokio = { version = "1.0", features = ["full", "test-util"] }

[features]
default = ["std"]
std = []
async = ["tokio"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

