//! Wire-format stability tests ("golden vectors").
//!
//! These pin the v2 formats produced by this crate: key derivation from
//! seeds, deterministic hybrid signatures, and decryption of a stored
//! envelope. If any of these fail after a code change, the wire format has
//! changed and the format version must be bumped — do not just update the
//! pinned values.

use quantum_shield::{verify, verify_rotation, Envelope, HybridCrypto};
use sha3::{Digest, Sha3_256};

/// A fixed test keypair from a QSK2 bundle with the given seed byte.
fn fixed_keypair_with(seed: u8) -> HybridCrypto {
    let mut secret = Vec::new();
    secret.extend_from_slice(b"QSK2");
    secret.push(2); // version
    secret.push(1); // suite
    secret.extend_from_slice(&[seed; 32]); // x25519
    secret.extend_from_slice(&[seed.wrapping_add(1); 64]); // ml-kem seed
    secret.extend_from_slice(&[seed.wrapping_add(2); 32]); // ed25519 seed
    secret.extend_from_slice(&[seed.wrapping_add(3); 32]); // ml-dsa seed
    HybridCrypto::from_secret_bytes(&secret).unwrap()
}

/// The primary fixed keypair (seeds 0x01/0x02/0x03/0x04).
fn fixed_keypair() -> HybridCrypto {
    fixed_keypair_with(0x01)
}

#[test]
fn key_derivation_is_stable() {
    let kp = fixed_keypair();
    let bundle = kp.public_keys().to_bytes();
    assert_eq!(bundle.len(), quantum_shield::PUBLIC_BUNDLE_LEN);
    assert_eq!(
        hex::encode(Sha3_256::digest(&bundle)),
        "2e2a8ceec37f7e0b8b68ed88fe9de8571c9a8ce35f7edb25a63e28409a9daa1b"
    );
}

#[test]
fn signing_is_deterministic_and_stable() {
    let kp = fixed_keypair();
    let sig1 = kp.sign(b"golden message", b"golden-context").unwrap();
    let sig2 = kp.sign(b"golden message", b"golden-context").unwrap();
    assert_eq!(sig1, sig2, "hybrid signing must be deterministic");

    let bytes = sig1.to_bytes();
    assert_eq!(
        hex::encode(Sha3_256::digest(&bytes)),
        "2beace633b94ff11268225cb31f487d6a9c04ea945e13a786b8fd011c1903dc8"
    );
    verify(
        b"golden message",
        b"golden-context",
        &sig1,
        kp.public_keys(),
    )
    .unwrap();
}

/// An envelope generated by quantum-shield 0.2.0 for the fixed keypair.
/// Every future version must keep decrypting it.
#[test]
fn stored_envelope_still_opens() {
    let kp = fixed_keypair();
    let hex_str = include_str!("data/envelope_v2.hex");
    let bytes = hex::decode(hex_str.trim()).unwrap();
    let envelope = Envelope::from_bytes(&bytes).unwrap();
    assert_eq!(
        kp.open(&envelope).unwrap(),
        b"quantum-shield v2 golden envelope"
    );
}

#[test]
fn key_id_is_stable() {
    let kp = fixed_keypair();
    assert_eq!(
        hex::encode(kp.public_keys().key_id().as_bytes()),
        "2e2a8ceec37f7e0b8b68ed88fe9de857"
    );
}

/// Rotation attestations are fully deterministic (deterministic hybrid
/// signing), so a fixed old→new rotation pins to an exact byte string.
#[test]
fn rotation_attestation_is_stable() {
    let old = fixed_keypair_with(0x01);
    let new = fixed_keypair_with(0x10);
    let att = old.attest_rotation(new.public_keys(), 1).unwrap();

    // Deterministic: same inputs, same attestation.
    let att2 = old.attest_rotation(new.public_keys(), 1).unwrap();
    assert_eq!(att, att2);

    assert_eq!(
        hex::encode(Sha3_256::digest(att.to_bytes())),
        "43fdb87805c2ce3caed21def1ff89d0eedc00d7c814be0cca243d80293343ddf"
    );
    // And it still verifies.
    assert_eq!(
        verify_rotation(old.public_keys(), &att).unwrap(),
        new.public_keys()
    );
}
